### ISSUE TITLE
Chef never successfully completed

### ISSUE THREAD

**Issue by john0609** [airbnb/smartstack-cookbook#15]
I am trying to test run smartstack but was never able to initiate VM. I always received the following error:
==> smartstack: [2015-03-31T18:53:25+00:00] INFO: Start handlers complete.
==> smartstack: [2015-03-31T18:53:26+00:00] WARN: Using java::default instead is recommended.
==> smartstack: [2015-03-31T18:53:26+00:00] WARN: Cloning resource attributes for runit_service[nerve] from prior resource (CHEF-3694)
==> smartstack: [2015-03-31T18:53:26+00:00] WARN: Previous runit_service[nerve]: /tmp/vagrant-chef/e1babbcb5045767b2dc1e294547a748b/cookbooks/smartstack/recipe
/nerve.rb:86:in `from_file'
==> smartstack: [2015-03-31T18:53:26+00:00] WARN: Current  runit_service[nerve]: /tmp/vagrant-chef/e1babbcb5045767b2dc1e294547a748b/cookbooks/smartstack/recipe
/test.rb:92:in `from_file'
==> smartstack: [2015-03-31T18:53:26+00:00] WARN: Cloning resource attributes for runit_service[synapse] from prior resource (CHEF-3694)
==> smartstack: [2015-03-31T18:53:26+00:00] WARN: Previous runit_service[synapse]: /tmp/vagrant-chef/e1babbcb5045767b2dc1e294547a748b/cookbooks/smartstack/reci
es/synapse.rb:119:in `from_file'
==> smartstack: [2015-03-31T18:53:26+00:00] WARN: Current  runit_service[synapse]: /tmp/vagrant-chef/e1babbcb5045767b2dc1e294547a748b/cookbooks/smartstack/reci
es/test.rb:96:in `from_file'
==> smartstack: [2015-03-31T18:58:54+00:00] INFO: Retrying execution of chef_gem[minitest-chef-handler], 0 attempt(s) left
==> smartstack: ================================================================================
==> smartstack: Recipe Compile Error in /tmp/vagrant-chef/e1babbcb5045767b2dc1e294547a748b/cookbooks/minitest-handler/recipes/default.rb
==> smartstack: ================================================================================
==> smartstack:
==> smartstack: LoadError
==> smartstack: ---------
==> smartstack: cannot load such file -- ci/reporter/minitest
==> smartstack:
==> smartstack: Cookbook Trace:
==> smartstack: ---------------
==> smartstack:   /tmp/vagrant-chef/e1babbcb5045767b2dc1e294547a748b/cookbooks/minitest-handler/recipes/default.rb:28:in `from_file'
==> smartstack:
==> smartstack: Relevant File Content:
==> smartstack: ----------------------
==> smartstack: /tmp/vagrant-chef/e1babbcb5045767b2dc1e294547a748b/cookbooks/minitest-handler/recipes/default.rb:
==> smartstack:
==> smartstack:  21:    # attempt still fails with the error in that thread, however
==> smartstack:  22:    # the retry succeeds...
==> smartstack:  23:    retries 1
==> smartstack:  24:  end.run_action(:install)
==> smartstack:  25:
==> smartstack:  26:  Gem.clear_paths
==> smartstack:  27:  # Ensure minitest gem is utilized
==> smartstack:  28>> require "minitest-chef-handler"
==> smartstack:  29:
==> smartstack:  30:  scratch_dir = ::File.join(Chef::Config[:file_cache_path], "minitest_scratch")
==> smartstack:  31:
==> smartstack:  32:  [:delete, :create].each do |action|
==> smartstack:  33:    directory "#{action} minitest test location" do
==> smartstack:  34:      path node[:minitest][:path]
==> smartstack:  35:      owner node[:minitest][:owner]
==> smartstack:  36:      group node[:minitest][:group]
==> smartstack:  37:      mode node[:minitest][:mode]
==> smartstack: [2015-03-31T18:58:56+00:00] ERROR: Running exception handlers
==> smartstack: [2015-03-31T18:58:56+00:00] ERROR: Exception handlers complete
==> smartstack: [2015-03-31T18:58:56+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> smartstack: [2015-03-31T18:58:56+00:00] FATAL: LoadError: cannot load such file -- ci/reporter/minitest
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

I am using windows 7 and I was able to start the zookeeper easily.

**Comment by jralph** [comment]
Also getting this error. Any solution?
